---
- hosts: spines
  gather_facts: false
  tasks:
    - name: Get EOS Facts
      eos_facts:
    
    - debug:
        var: ansible_net_all_ipv4_addresses

    - debug:
        var: ansible_net_version